import mongoose from "mongoose";
import crypto from "crypto";

const BrandingSchema = new mongoose.Schema(
  {
    logo: {
      provider: String,
      id: String,
      url: String,
      alt: String,
      width: Number,
      height: Number,
    },
    primaryColor: {
      type: String,
      default: "#3B82F6", // Default blue
    },
    secondaryColor: {
      type: String,
      default: "#10B981", // Default green
    },
    accentColor: {
      type: String,
      default: "#F59E0B", // Default amber
    },
    favicon: {
      url: String,
      publicId: String,
    },
    heroImages: [
      {
        provider: String,
        id: String,
        url: String,
        alt: String,
        width: Number,
        height: Number,
        order: Number,
      },
    ],
  },
  { _id: false }
);

const DomainSchema = new mongoose.Schema(
  {
    domain: {
      type: String,
      required: true,
      // Note: unique constraint removed - enforced at application level via validateDomainUniqueness()
      lowercase: true,
      trim: true,
    },
    isPrimary: {
      type: Boolean,
      default: false,
    },
    verified: {
      type: Boolean,
      default: false,
    },
    verificationToken: String,
    verifiedAt: Date,
  },
  { _id: true }
);

const TenantSchema = new mongoose.Schema(
  {
    // Basic tenant information
    name: {
      type: String,
      required: true,
      trim: true,
    },
    slug: {
      type: String,
      required: false, // Generated by pre-save hook
      unique: true,
      lowercase: true,
      trim: true,
      index: true,
    },
    // Business information
    businessName: {
      type: String,
      required: true,
      trim: true,
    },
    businessType: {
      type: String,
      enum: ["salon", "spa", "clinic", "studio", "other"],
      default: "salon",
    },
    description: String,
    email: {
      type: String,
      required: true,
      lowercase: true,
      trim: true,
    },
    phone: String,
    address: {
      street: String,
      city: String,
      state: String,
      postalCode: String,
      country: {
        type: String,
        default: "United Kingdom",
      },
    },
    // Timezone and locale
    timezone: {
      type: String,
      default: "Europe/London",
    },
    locale: {
      type: String,
      default: "en-GB",
    },
    currency: {
      type: String,
      enum: ["GBP", "EUR", "USD"],
      default: "GBP",
    },
    // Domains - custom domain support
    domains: [DomainSchema],
    // Branding
    branding: {
      type: BrandingSchema,
      default: () => ({}),
    },
    // Subscription and billing
    plan: {
      type: String,
      enum: ["trial", "starter", "professional", "enterprise"],
      default: "trial",
    },
    planStartDate: Date,
    planEndDate: Date,
    // Stripe Connect account for platform fees
    stripeAccountId: {
      type: String,
      index: true,
    },
    stripeCustomerId: String, // For billing the tenant
    // Business hours (default for the salon)
    defaultWorkingHours: [
      {
        dayOfWeek: { type: Number, min: 0, max: 6 }, // 0=Sunday, 6=Saturday
        start: String, // HH:mm format
        end: String, // HH:mm format
        _id: false,
      },
    ],
    // Scheduling settings
    schedulingSettings: {
      allowOnlineBooking: { type: Boolean, default: true },
      requireDeposit: { type: Boolean, default: true },
      depositPercentage: { type: Number, default: 0, min: 0, max: 100 }, // 0 = fixed amount
      depositAmount: { type: Number, default: 0 }, // Fixed deposit amount in pence
      bookingBuffer: { type: Number, default: 15 }, // Minutes buffer between appointments
      maxAdvanceBookingDays: { type: Number, default: 60 },
      minAdvanceBookingHours: { type: Number, default: 2 },
      cancellationPolicyHours: { type: Number, default: 24 },
      showBeauticianPhotos: { type: Boolean, default: true },
      allowBeauticianSelection: { type: Boolean, default: true },
    },
    // Payment settings
    paymentSettings: {
      acceptOnlinePayments: { type: Boolean, default: true },
      acceptCash: { type: Boolean, default: true },
      acceptCardInSalon: { type: Boolean, default: true },
      platformFeePerBooking: { type: Number, default: 50 }, // £0.50 in pence
      platformFeePerProduct: { type: Number, default: 50 }, // £0.50 in pence
    },
    // Status
    status: {
      type: String,
      enum: ["active", "suspended", "cancelled", "trial"],
      default: "trial",
      index: true,
    },
    active: {
      type: Boolean,
      default: true,
      index: true,
    },
    // Owner reference (primary admin)
    ownerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Admin",
      index: true,
    },
    // Statistics
    stats: {
      totalBookings: { type: Number, default: 0 },
      totalRevenue: { type: Number, default: 0 },
      totalBeauticians: { type: Number, default: 0 },
      totalClients: { type: Number, default: 0 },
    },
    // SEO settings per tenant
    seo: {
      metaTitle: String,
      metaDescription: String,
      keywords: [String],
      ogImage: {
        url: String,
        publicId: String,
      },
      structuredData: mongoose.Schema.Types.Mixed,
    },
    // Feature flags
    features: {
      enableBlog: { type: Boolean, default: false },
      enableProducts: { type: Boolean, default: true },
      enableGiftCards: { type: Boolean, default: false },
      enableMemberships: { type: Boolean, default: false },
      enableReviews: { type: Boolean, default: true },
      enableLoyaltyProgram: { type: Boolean, default: false },
      // Platform Features
      smsConfirmations: { type: Boolean, default: false },
      smsReminders: { type: Boolean, default: false },
      onlinePayments: { type: Boolean, default: true },
      emailNotifications: { type: Boolean, default: true },
    },
    // Trial and demo flags
    isTrial: {
      type: Boolean,
      default: true,
    },
    trialEndsAt: Date,
    isDemo: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes for performance
TenantSchema.index({ slug: 1 }, { unique: true });
// Note: domains.domain index NOT defined here - managed programmatically to avoid duplicate key issues with undefined/null
TenantSchema.index({ status: 1, active: 1 });
TenantSchema.index({ ownerId: 1 });
TenantSchema.index({ createdAt: -1 });

// Generate slug from name if not provided
TenantSchema.pre("save", async function (next) {
  console.log("[Tenant Pre-Save] ============ START ============");
  console.log("[Tenant Pre-Save] Document ID:", this._id);
  console.log("[Tenant Pre-Save] isNew:", this.isNew);
  console.log("[Tenant Pre-Save] Current slug:", this.slug);
  console.log("[Tenant Pre-Save] Name:", this.name);
  console.log("[Tenant Pre-Save] BusinessName:", this.businessName);

  if (!this.slug && this.name) {
    console.log("[Tenant Pre-Save] No slug found, generating from name...");
    
    // Create slug from name
    let baseSlug = this.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");

    console.log("[Tenant Pre-Save] Generated base slug:", baseSlug);
    
    if (!baseSlug || baseSlug.length === 0) {
      console.error("[Tenant Pre-Save] ERROR: Base slug is empty after transformation!");
      console.error("[Tenant Pre-Save] ERROR: Original name was:", this.name);
      return next(new Error("Unable to generate slug from name"));
    }

    let slug = baseSlug;
    let counter = 1;

    console.log("[Tenant Pre-Save] Checking slug uniqueness...");
    
    // Check if slug exists and add counter if needed
    // Use lean() to bypass tenant filtering middleware
    while (await mongoose.models.Tenant.findOne({ slug }).lean()) {
      console.log(
        "[Tenant Pre-Save] Slug '",
        slug,
        "' already exists, trying:",
        `${baseSlug}-${counter}`
      );
      slug = `${baseSlug}-${counter}`;
      counter++;
      
      if (counter > 100) {
        console.error("[Tenant Pre-Save] ERROR: Too many slug collisions (>100)!");
        return next(new Error("Unable to generate unique slug"));
      }
    }

    this.slug = slug;
    console.log("[Tenant Pre-Save] ✓ Final slug set to:", this.slug);
  } else if (!this.slug && !this.name) {
    console.error("[Tenant Pre-Save] ERROR: No slug and no name provided!");
    return next(new Error("Either slug or name must be provided"));
  } else {
    console.log("[Tenant Pre-Save] Slug already exists, skipping generation:", this.slug);
  }

  // Validate slug is set
  if (!this.slug) {
    console.error("[Tenant Pre-Save] ============ ERROR ============");
    console.error("[Tenant Pre-Save] ERROR: No slug set after all processing!");
    console.error("[Tenant Pre-Save] ERROR: Name:", this.name);
    console.error("[Tenant Pre-Save] ERROR: BusinessName:", this.businessName);
    console.error("[Tenant Pre-Save] ========================================");
    return next(new Error("Slug must be set before saving"));
  }

  console.log("[Tenant Pre-Save] ✓ Validation passed");
  console.log("[Tenant Pre-Save] ✓ Final slug:", this.slug);
  console.log("[Tenant Pre-Save] ============ END ============");

  // Clean up domains array - remove if null or empty to avoid duplicate key errors on sparse index
  if (
    !this.domains ||
    (Array.isArray(this.domains) && this.domains.length === 0)
  ) {
    this.domains = undefined; // Sparse index ignores undefined, preventing duplicate null keys
  } // Set trial end date if not set
  if (this.isTrial && !this.trialEndsAt) {
    this.trialEndsAt = new Date(Date.now() + 14 * 24 * 60 * 60 * 1000); // 14 days
  }

  next();
});

// Method to check if tenant is active
TenantSchema.methods.isActive = function () {
  return this.active && this.status === "active";
};

// Method to check if trial has expired
TenantSchema.methods.isTrialExpired = function () {
  return this.isTrial && this.trialEndsAt && this.trialEndsAt < new Date();
};

// Method to generate domain verification token
TenantSchema.methods.generateDomainVerificationToken = function () {
  return crypto.randomBytes(32).toString("hex");
};

// Don't return sensitive data in JSON
TenantSchema.methods.toJSON = function () {
  const obj = this.toObject();
  // Remove sensitive fields if needed
  return obj;
};

const Tenant = mongoose.model("Tenant", TenantSchema);

// Production-ready domain uniqueness: Use application-level validation instead of DB index
// to avoid MongoDB sparse index issues with undefined/null values
Tenant.prototype.validateDomainUniqueness = async function () {
  if (this.domains && this.domains.length > 0) {
    for (const domainObj of this.domains) {
      if (domainObj.domain) {
        const existing = await Tenant.findOne({
          "domains.domain": domainObj.domain,
          _id: { $ne: this._id },
        }).lean();
        if (existing) {
          throw new Error(
            `Domain ${domainObj.domain} is already in use by another tenant`
          );
        }
      }
    }
  }
};

export default Tenant;
